### ISSUE TITLE
[Bug] Press [E] to access the Ammu-Nation

### ISSUE THREAD

**Issue by NexDK** [esx-framework/esx_weaponshop#21]
**The "Press [E] to access the Ammu-Nation" doesn't go away while in the buy menu.**

![Skærmbillede 2023-10-19 084048](https://github.com/esx-framework/esx_weaponshop/assets/36231983/e797a2f7-7f7b-4382-ba11-7c57520b3002)

**The "Press [E] to access the Ammu-Nation" keep staying on the screen when not in the marker/ring.**

![Skærmbillede 2023-10-19 084103](https://github.com/esx-framework/esx_weaponshop/assets/36231983/50f83b31-a3b3-43a9-b440-faac7bd5d261)

**Comment by Gellipapa** [comment]
@StupidRepo Hi! Yes it's no problem i will fix but i need more time.

**Comment by Gellipapa** [comment]
@NexDK Hi! I fixed problem you should download latest version and works perfectly. Thank you for reported issue.

**Comment by NexDK** [comment]
Amazing thanks 👍
